# This workflow will install Python dependencies, run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
            python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Download test data
        run: |
            cd znmdakit-examples
            dvc pull
      - name: Run tests
        run: |
            cd znmdakit-examples
            dvc repro -f
